server:
  port: 8088
  servlet:
    # 应用的访问路径
    context-path: /
  error:
    whitelabel:
      enabled: true
spring:
  profiles:
    active: @profiles.active@
  mvc:
    throw-exception-if-no-handler-found: true
    path match:
      matching-strategy: ANT_PATH_MATCHER
  web:
    resources:
      add-mappings: false

  jackson:
    # 日期格式化
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      # 格式化输出
      indent_output: false
      # 忽略无法转换的对象
      fail_on_empty_beans: false
    deserialization:
      # 允许对象忽略json中不存在的属性
      fail_on_unknown_properties: false

--- # knife4j配置
knife4j:
  enable: true

# security配置
security:
  # 排除路径
  excludes:
    - /swagger-ui/**
    - /swagger-resources/**
    # 静态资源
    - /*.html
    - /**/*.html
    - /**/*.css
    - /**/*.js
    # 公共路径
    - /favicon.ico
    - /error
    # swagger 文档配置
    - /*/api-docs
    - /*/api-docs/**
    # actuator 监控配置
    - /actuator
    - /actuator/**


