server:
  port: 8088
  servlet:
    # 应用的访问路径
    context-path: /
  error:
    whitelabel:
      enabled: false
spring:
  profiles:
    active: @profiles.active@
  devtools:
    restart:
      enabled: true
  thymeleaf:
    cache: false

--- # knife4j配置
knife4j:
  enable: true


