spring:
  devtools:
    restart:
      enabled: true
  datasource:
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/spring-test?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    type: com.zaxxer.hikari.HikariDataSource #当前使用的数据源 Hikari
    hikari:
      minimum-idle: 1 #	池中维护的最小空闲连接数 默认10 根据实际情况来
      maximum-pool-size: 10 # 池中最大连接数    根据实际情况来
      auto-commit: true  # 自动提交从池中返回的连接
      idle-timeout: 600000 # 一个连接idle状态的最大时长（毫秒），超时则被释放（retired），缺省:10分钟
      max-lifetime: 1800000 # 一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒，参考MySQL
      connection-timeout: 30000   # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 缺省:30秒
      connection-test-query: select 1
      read-only: false      # 是否是只读
  redis:
    host: 127.0.0.1
    database: 0
    port: 6379
    password: 12345678
    # 连接超时时间
    timeout: 10s
    lettuce:
        pool:
          # 连接池最大连接数
          max-active: 200
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
          # 连接池中的最大空闲连接
          max-idle: 10
          # 连接池中的最小空闲连接
          min-idle: 0

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 自动驼峰命名规则（camel case）映射
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: deletedAt # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: NOW() # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 'NULL' # 逻辑未删除值(默认为 0)
      id-type: auto


#Sa-Token配置
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: Authorization
  # token有效期，单位秒，-1代表永不过期
  timeout: 86400
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号并发登录 (为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为false时每次登录新建一个token)
  is-share: false
  # 是否输出操作日志
  is-log: false
  # 是否从cookie中读取token
  is-read-cookie: false
  # 是否尝试从header里读取token
  is-read-header: true
  # token前缀
  token-prefix: "Bearer"
  # jwt秘钥
  jwt-secret-key: sdkjfalksdjf3242323kjksdfkasjd712312


# security配置
security:
  # 排除路径
  excludes:
    - /swagger-ui/**
    - /swagger-resources/**
    # 静态资源
    - /*.html
    - /**/*.html
    - /**/*.css
    - /**/*.js
    # 公共路径
    - /favicon.ico
    - /error
    # swagger 文档配置
    - /*/api-docs
    - /*/api-docs/**
    # actuator 监控配置
    - /actuator
    - /actuator/**

wx:
  miniapp:
    configs:
      - appid: 111
        secret: 111
        token: 111
        aesKey: 1111
        msgDataFormat: JSON
        storageType: Jedis
        storageKeyPrefix: xb
        storageRedisHost: 127.0.0.1
        storageRedisPort: 6379
        storageRedisPassword: 12345678
#wechat配置
logging:
  config: classpath:logback-plus.xml
  level:
    org.springframework.web: info
    com.github.binarywang.demo.wx.miniapp: debug
    cn.binarywang.wx.miniapp: debug


