server:
  port: 8088
  servlet:
    # 应用的访问路径
    context-path: /
  error:
    whitelabel:
      enabled: false
spring:
  profiles:
    active: @profiles.active@

--- # knife4j配置
knife4j:
  enable: true


