server:
  port: 8088
  servlet:
    # 应用的访问路径
    context-path: /
  error:
    whitelabel:
      enabled: false
spring:
  profiles:
    active: @profiles.active@
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

  jackson:
    # 日期格式化
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      # 格式化输出
      indent_output: false
      # 忽略无法转换的对象
      fail_on_empty_beans: false
    deserialization:
      # 允许对象忽略json中不存在的属性
      fail_on_unknown_properties: false

--- # knife4j配置
knife4j:
  enable: true


